FROM tomcat:8.0.36-jre8
RUN rm -rf /usr/local/tomcat/webapps/*
ADD web-app/log4shell-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
RUN echo "Je suis là !!!" > /home/flag
EXPOSE 8080
CMD ["catalina.sh", "run"]
