FROM openjdk:8-jdk-slim
RUN apt-get update && \
    apt-get install -y python3.9 python3-pip curl netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir colorama argparse
COPY exploit.py /app/exploit.py
COPY marshalsec-0.0.3-SNAPSHOT-all.jar /app/marshalsec-0.0.3-SNAPSHOT-all.jar
WORKDIR /app
ENV USER_IP="localhost"
RUN java -version
RUN javac -version
RUN curl --version
RUN nc -h
CMD ["tail", "-f", "/dev/null"]
